@startuml

class PropertyValue {
-name:String
-value:Object
}

interface PropertyValues


class MutablePropertyValues


PropertyValues <|-- MutablePropertyValues
PropertyValue *-- MutablePropertyValues

@enduml