@startuml

class HandlerMethod

class InvocableHandlerMethod

HandlerMethod <|-- InvocableHandlerMethod

class ServletInvocableHandlerMethod

InvocableHandlerMethod <|-- ServletInvocableHandlerMethod


@enduml