@startuml

/'abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}'/


interface BeanDefinition

abstract class AbstractBeanDefinition

BeanDefinition <|-- AbstractBeanDefinition

class RootBeanDefinition
AbstractBeanDefinition <|-- RootBeanDefinition

class ChildBeanDefinition
AbstractBeanDefinition <|-- ChildBeanDefinition
@enduml