@startuml


interface PlatformTransactionManager {
    + getTransaction(TransactionDefinition definition):TransactionStatus
    + commit(TransactionStatus status)
    + rollback(TransactionStatus status)
}

abstract class AbstractPlatformTransactionManager

PlatformTransactionManager <|-- AbstractPlatformTransactionManager

class DataSourceTransactionManager

AbstractPlatformTransactionManager <|-- DataSourceTransactionManager

@enduml