@startuml

/'abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}'/


abstract class AbstractOwnableSynchronizer

AbstractOwnableSynchronizer <|-- AbstractQueuedSynchronizer

abstract class AbstractQueuedSynchronizer
/' 传说中的AQS '/

abstract class Sync

AbstractQueuedSynchronizer <|- Sync

class FairSync
Sync <|-- FairSync
class NonfairSync
Sync <|-- NonfairSync

class ReentrantLock

FairSync *-- ReentrantLock
NonfairSync *-- ReentrantLock

interface Lock

Lock <|-- ReentrantLock
@enduml