@startuml

/'abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}'/



interface ChannelHandler
interface ChannelInboundHandler
ChannelHandler <|-- ChannelInboundHandler
/'class ChannelInboundHandlerAdapter
ChannelInboundHandler <|-- ChannelInboundHandlerAdapter'/

interface ChannelOutboundHandler
ChannelHandler <|-- ChannelOutboundHandler

interface ChannelHandlerContext
/'abstract class AbstractChannelHandlerContext
ChannelHandlerContext <|-- AbstractChannelHandlerContext'/


interface ChannelPipeline
class DefaultChannelPipeline
ChannelPipeline <|- DefaultChannelPipeline

class HeadContext
HeadContext *-- DefaultChannelPipeline
/'AbstractChannelHandlerContext <|-- HeadContext'/

ChannelHandlerContext <|-- HeadContext
ChannelInboundHandler <|-- HeadContext
ChannelOutboundHandler <|-- HeadContext

interface ChannelInboundInvoker
interface ChannelOutboundInvoker
ChannelInboundInvoker <|-- ChannelHandlerContext
ChannelOutboundInvoker <|-- ChannelHandlerContext

ChannelInboundInvoker <|-- ChannelPipeline
ChannelOutboundInvoker <|-- ChannelPipeline
@enduml